const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const port = 25565;

app.set('view engine', 'ejs')
app.use(bodyParser.urlencoded())

app.use(express.static(__dirname + 'views'))

app.listen(port, function () {
    console.log('App listening on port: ', port);
});

app.get('/', (req, res) => {
    var maos = [
        'Sua mão Esquerda',
        'Sua mão Direita',
    ]
    var objetos = [
        'Um Anel',
        'Um Ankh',
        'Um Cálice',
        'Um Candelabro',
        'Um Cetro',
        'Um Cilindro',
        'Um Cone',
        'Um Copo',
        'Um Crânio',
        'Um Cubo',
        'Um Dodecaedro (d12)',
        'Um Escudo',
        'Um Espelho',
        'Um Icosaedro (d20)',
        'Um Livro',
        'Um Machado',
        'Um Octaedro (d8)',
        'Um Ovo',
        'Um Parafuso',
        'Um Peão',
        'Um Prato',
        'Um Tetraedro (d4)',
        'Um Tridente',
        'Uma Adaga',
        'Uma Âncora',
        'Uma Cabeça',
        'Uma Caneca',
        'Uma Colher',
        'Uma Concha',
        'Uma Cruz',
        'Uma Esfera',
        'Uma Esfinge',
        'Uma Espada',
        'Uma Estátua de Buda',
        'Uma Estrela',
        'Uma Foice',
        'Uma Fruta',
        'Uma Garrafa',
        'Uma Maçã',
        'Uma Mão',
        'Uma Moeda',
        'Uma Pedra',
        'Uma Pirâmide de base hexagonal',
        'Uma Pirâmide de base quadrada',
        'Uma Rosa',
        'Uma Taça',
        'Uma Vela',
    ]
    var materiais = [
        'de Aço Escovado',
        'de Acrílico',
        'de Alumínio',
        'de Âmbar',
        'de Areia Compactada',
        'de Barro',
        'de Carvão',
        'de Cerâmica',
        'de Chocolate',
        'de Chumbo',
        'de Cobre',
        'de Cobre envelhecido',
        'de Concreto',
        'de Coral',
        'de Cota-de-malha de metal',
        'de Couro',
        'de Cristal',
        'de Cristal Negro',
        'de Esmeralda',
        'de Esponja',
        'de Estanho',
        'de Ferro',
        'de Ferro Enferrujado',
        'de Gelatina',
        'de Gelo',
        'de Gesso',
        'de Grafite',
        'de Granito',
        'de Hematita',
        'de Isopor',
        'de Jade',
        'de Lápis-Lazuli',
        'de Madeira Clara',
        'de Madeira Escura',
        'de Marfim',
        'de Mármore Branco',
        'de Mármore Negro',
        'de Mármore Verde',
        'de Obsidiana',
        'de Ônix',
        'de Osso',
        'de Ouro',
        'de Palha',
        'de Papel',
        'de Parafina',
        'de Pasta de Dente',
        'de Pedra-Pomes',
        'de Plástico',
        'de Prata',
        'de Prata muito oxidada',
        'de Prata Oxidada',
        'de Quartzo Rosa',
        'de Quartzo Roxo',
        'de Rubi',
        'de Safira',
        'de Terra úmida',
        'de Tijolo',
        'de Topázio',
        'de Vidro',
        'de Vidro Jateado',
        'de Vidro trincado',
        'de Vinil',
    ]
    var tamanhos = [
        '1 cm',
        '2 cm',
        '3 cm',
        '4 cm',
        '5 cm',
        '6 cm',
        '7 cm',
        '8 cm',
        '9 cm',
        '10 cm',
        '11 cm',
        '12 cm',
        '13 cm',
        '14 cm',
        '15 cm',
        '16 cm',
        '17 cm',
        '18 cm',
        '19 cm',
        '20 cm',
    ]
    var cores = [
        'Amarela',
        'Azul',
        'Branca',
        'Cinza',
        'Dourada',
        'Índigo',
        'Laranja',
        'Prateada',
        'Preta',
        'Rosa',
        'Roxa',
        'Verde',
        'Vermelha',
        'Violeta',
    ]
    var simbolos = [
        'Alquímico da água',
        'Alquímico da terra',
        'Alquímico do ar',
        'Alquímico do fogo',
        'da Lua',
        'da Terra',
        'de Júpiter',
        'de Marte',
        'de Mercúrio',
        'de Netuno',
        'de Plutão',
        'de Saturno',
        'de Saturno',
        'de Um Heptagrama',
        'de Um Hexagrama',
        'de Um Pentagrama',
        'de Uma espiral',
        'de Urano',
        'de Vênus',
        'do Número 1',
        'do Número 2',
        'do Número 3',
        'do Número 4',
        'do Número 5',
        'do Número 6',
        'do Número 7',
        'do Número 8',
        'do Número 9',
        'do Sol',
        'de Aquário',
        'de Áries',
        'de Câncer',
        'de Capricórnio',
        'de Escorpião',
        'de Gêmeos',
        'de Leão',
        'de Libra',
        'de Peixes',
        'de Sagitário',
        'de Touro',
        'de Virgem',
        'de Virgem',
        'de PI',
    ]
    var preenchimento = [
        'Em 1/3',
        'Até a Metade',
        'Em 2/3',
    ]
    var subtancia = [
        'Absinto',
        'Açúcar',
        'Água',
        'Água com Gás',
        'Água do Mar',
        'Água Suja',
        'Álcool',
        'Licor de Amarula',
        'Areia','Azeite',
        'Azeite de Dendê',
        'Bolinhas de Gude',
        'Bolinhas de Sabão',
        'Bolinhas de Luz Branca',
        'Cabelo',
        'Café',
        'Café com Leite',
        'Calda de caramelo',
        'Calda de chocolate',
        'Castanhas',
        'Catchup',
        'Cera derretida',
        'Cerveja',
        'Cerveja Escura',
        'Chá de Erva-Doce',
        'Chá de Jasmim',
        'Chá Mate',
        'Chocolate granuado',
        'Creme de Abacate',
        'Coca-cola',
        'Creme de Avelã',
        'Creme de Ervilha',
        'Creme de Milho',
        'Doces',
        'Esferas de cristal',
        'Farinha',
        'Fermento',
        'Folhas',
        'Folhas Secas',
        'Formigas',
        'Floquinhos de Neve',
        'Gasolina',
        'Geléia de Abacaxi',
        'Geléia de Laranja',
        'Geléia de mocotó',
        'Geléia de Morango',
        'Grãos de Arroz',
        'Grãos de Feijão',
        'Grãos de Milho',
        'Groselha',
        'Guaraná',
        'Hidratante',
        'Larvas',
        'Lascas de vidro',
        'Leite',
        'Leite de Coco',
        'Maionese',
        'Mel',
        'Minhocas',
        'Mostarda',
        'Papel picado',
        'Óleo de Girassol',
        'Pasta de Amendoim',
        'Pedras brancas',
        'Pedrinhas',
        'Peixes',
        'Penas brancas',
        'Penas coloridas',
        'Penas pretas',
        'Perfume',
        'Pétalas de Rosa',
        'Petróleo',
        'Pimenta',
        'Pinga',
        'Plástico derretido',
        'Protetor Solar',
        'Queijo derretido',
        'Querosene',
        'Restos de Comida',
        'Sabonete líquido',
        'Sal',
        'Sangue',
        'Sementes de Alpiste',
        'Sementes de Maçã',
        'Sementes de Melancia',
        'Silicone',
        'Sorvete de Chocolate',
        'Suco de abacaxi',
        'Suco de Acerola',
        'Suco de Cenoura',
        'Suco de Laranja',
        'Suco de Limão',
        'Suco de Maçã',
        'Suco de Morango',
        'Suco de Tomate',
        'Suco de Uva',
        'Vapor',
        'Vinho Branco',
        'Vinho Tinto',
        'Vitamina de Banana',
        'Vodka',
        'Xarope',
        'Tachinhas',
        'Lantejoulas',
    ]

    var propriedades = [
        'Oco(a)',
        'Oco(a), Vazio',
        'Sólido(a)',
        'Transparente',
        'Translúcido(a)',
        'Muito Brilhante, iluminando todo o ambiente',
        'Levemente Brilhante, iluminando pouco menos que a mesa',
    ]
    res.render('index.ejs', {maos, objetos, materiais, tamanhos, cores, simbolos, preenchimento, subtancia, propriedades});
});

